image: node:latest

build-frontend:       # This job runs in the build stage, which runs first.
  stage: build
  only:
    changes:
      - frontend/**/*
  artifacts:
    untracked: true
    paths:
      - build/
    exclude:
      - "node_modules/**/*"
  before_script:
    - cd frontend
  script:
    - echo "Compiling the code..."
    - npm install
    - npm run build
    - echo "Compile complete."

deploy-frontend:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    changes:
      - frontend/**/*
    refs:
      - main
  dependencies:
    - "build-frontend"
  script:
    - echo "Deploying container to s3"
    - aws s3 sync build/ s3://$AWS_S3_BUCKET_NAME/main/latest
    - aws cloudfront create-invalidation --distribution-id $AWS_DISTRIBUTION_ID --paths "/main/latest/index.html"
    - echo "Deploy done for container"

