
build-backend:       # This job runs in the build stage, which runs first.
  image: public.ecr.aws/sam/build-nodejs18.x
  stage: build
  only:
    changes:
      - backend/**/*
  artifacts:
    untracked: true
    paths:
      - ./
    exclude:
      - "node_modules/**/*"
  before_script:
    - cd backend
  script:
    - echo "Compiling the code..."
    - sam build
    - echo "Compile complete."

deploy-backend:
  stage: deploy
  image: public.ecr.aws/sam/build-nodejs18.x
  only:
    changes:
      - backend/**/*
    refs:
      - main
  dependencies:
    - "build-backend"
  before_script:
    - cd backend
  script:
    - echo "Deploying container to s3"
    - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
    - echo "Deploy done for container"

