AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "backend\nSample SAM Template for backend\n"
Globals:
  Function:
    Timeout: 3
Resources:
  FilamentGET:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /filament
            Method: get
      CodeUri: s3://3dpdashboard/714c39afdb90f1dbc187199fdb08a05a
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./filament/GET
      Dockerfile: Dockerfile
  FilamentPOST:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /filament
            Method: post
      CodeUri: s3://3dpdashboard/714c39afdb90f1dbc187199fdb08a05a
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./filament/POST
      Dockerfile: Dockerfile
Outputs:
  FilamentApi:
    Description: API Gateway endpoint URL for Prod stage for Filament functions
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/filament/
