AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend

  Sample SAM Template for backend
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  FilamentGET:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: filament/GET/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Filament:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /filament
            Method: get
  FilamentPOST:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: filament/POST/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Filament:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /filament
            Method: post
  FilamentOPTIONS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: filament/OPTIONS/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        Filament:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties: 
            Path: /filament
            Method: options
  FilamentByIdGET:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: filament/byid/GET
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Filament:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /filament/{id}
            Method: get
  FilamentByIdOPTIONS:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: filament/byid/OPTIONS
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Filament:
          Type: Api 
          Properties:
            Path: /filament/{id}
            Method: options
  FilamentByIdDELETE:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: filament/byid/DELETE
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Filament:
          Type: Api 
          Properties:
            Path: /filament/{id}
            Method: delete




  PrintersGET:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: printers/GET/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Printers:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /printers
            Method: get
  PrintersPOST:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: printers/POST/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Printers:
          Type: Api
          Properties:
            Path: /printers
            Method: post
  PrintersOPTIONS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: printers/OPTIONS/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        Printers:
          Type: Api 
          Properties: 
            Path: /printers
            Method: options
  PrintersByIdGET:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: printers/byid/GET
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Printers:
          Type: Api
          Properties:
            Path: /printers/{id}
            Method: get
  PrintersByIdOPTIONS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: printers/byid/OPTIONS
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Printers:
          Type: Api 
          Properties:
            Path: /printers/{id}
            Method: options
  PrintersByIdDELETE:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: printers/byid/DELETE
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Printers:
          Type: Api 
          Properties:
            Path: /printers/{id}
            Method: delete
  DashboardGET:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dashboard/GET
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Printers:
          Type: Api
          Properties:
            Path: /dashboard
            Method: get
  DashboardOPTIONS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dashboard/OPTIONS
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Printers:
          Type: Api 
          Properties:
            Path: /dashboard
            Method: options            