AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  backend

  Sample SAM Template for backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  LogPrint:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: logprint
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        LogPrintPost:
          Type: Api
          Properties:
            Path: /logprint
            Method: POST
        LogPrintOptions:
          Type: Api
          Properties:
            Path: /logprint
            Method: options

  MainHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handler/build
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        DashboardGet:
          Type: Api
          Properties:
            Path: /dashboard
            Method: get
        DashboardOptions:
          Type: Api
          Properties:
            Path: /dashboard
            Method: options
        PrintsGet:
          Type: Api
          Properties:
            Path: /prints
            Method: get
        PrintsOptions:
          Type: Api
          Properties:
            Path: /prints
            Method: options
        PrintsPost:
          Type: Api
          Properties:
            Path: /prints
            Method: POST
        PrintsByIdGet:
          Type: Api
          Properties:
            Path: /prints/{id}
            Method: get
        PrintsByIdOptions:
          Type: Api
          Properties:
            Path: /prints/{id}
            Method: options
        PrintsByIdPost:
          Type: Api
          Properties:
            Path: /prints/{id}
            Method: post
        PrintsByIdDelete:
          Type: Api
          Properties:
            Path: /prints/{id}
            Method: delete
        FilamentGet:
          Type: Api
          Properties:
            Path: /filament
            Method: get
        FilamentPost:
          Type: Api
          Properties:
            Path: /filament
            Method: post
        FilamentByIDGet:
          Type: Api
          Properties:
            Path: /filament/{id}
            Method: get
        FilamentByIDDelete:
          Type: Api
          Properties:
            Path: /filament/{id}
            Method: delete
        FilamentByIDOptions:
          Type: Api
          Properties:
            Path: /filament/{id}
            Method: options
        FilamentOptions:
          Type: Api
          Properties:
            Path: /filament
            Method: options
        PrintersGet:
          Type: Api
          Properties:
            Path: /printers
            Method: get
        PrintersPost:
          Type: Api
          Properties:
            Path: /printers
            Method: post
        PrintersOptions:
          Type: Api
          Properties:
            Path: /printers
            Method: options
        PrintersByIDOptions:
          Type: Api
          Properties:
            Path: /printers/{id}
            Method: options
        PrintersByIDGet:
          Type: Api
          Properties:
            Path: /printers/{id}
            Method: get
        PrintersByIDDelete:
          Type: Api
          Properties:
            Path: /printers/{id}
            Method: delete
        PrintsByPrinterIdOptions:
          Type: Api
          Properties:
            Path: /printers/{id}/prints
            Method: options
        PrintsByPrinterIdGet:
          Type: Api
          Properties:
            Path: /printers/{id}/prints
            Method: get
